### ISSUE TITLE
Disable saving (tensorboard) log files

### ISSUE THREAD

**Issue by Lucaweihs** [allenai/allenact#113]
## Problem

We should be able to disable tensorboard logging from the command line. We also need the option to skip other type of logging (e.g. saving to the `used_configs` folder).

## Solution

Hopefully this is as easy as passing a few additional parameters to the runner.

## Dependencies

None

**Comment by jordis-ai2** [comment]
I just added two options (`-i` to disable tensorboard logging, `-a` to disable saving the used configs).
Currently, I still let the engine collect visualization data if a visualizer is present in machine params, but I could avoid it by passing a flag from runner if that's not sufficiently efficient...
