### ISSUE TITLE
RoboTHOR PointNav SuperSmall dataset

### ISSUE THREAD

**Issue by anikem** [allenai/allenact#134]
Create a subset of the RoboTHOR dataset, that trains to a high success value in a few minutes on CPU.
This dataset will be useful for debugging.

**Comment by Lucaweihs** [comment]
Partially solved by the introduction of the `dataset/robothor/pointnav/debug` dataset in 8fe8f53. As training to high success using RL in a few minutes with only a CPU takes a little work (even in simplified settings) I'm postponing this to 0.1.1.

**Comment by Lucaweihs** [comment]
On the debug dataset for RoboTHOR PointNav and was able to train to 50% accuracy in 40 minutes and >95% accuracy in 1.5 hours. This isn't quite at the level of "a few minutes" but I think works well enough for now so I will close this issue.
