### ISSUE TITLE
Remove Distance Caching for RoboTHOR and iTHOR Navigation Tasks and Rely Solely on the Built in Navmeshes

### ISSUE THREAD

**Issue by klemenkotar** [allenai/allenact#197]
## Problem

Currently AllenAct is using pre-computed distance caches as the default way of finding the distance between any point in the scene and the target. It has been shown that these caches offer little in the way of FPS improvements and makes the model train slower (in terms of number of steps). They are also tied to a specific release of ai2thor and awkward to use.

## Desired solution

iTHOR has now built in navmeshes for local path finding, and RoboTHOR has had this feature for some time. We can now use these native Unity methods to efficiently find a good distance to the target that can be used in the reward function and the SPL calculation.

## What This Requires

1. Updating the task sampler and task code for all the navigation tasks
2. Removing the distance caches from the online dataset files
3. Re-Generating the PointNav and ObjectNav datasets for iTHOR and RoboTHOR using the new distance + path finding function

**Comment by Lucaweihs** [comment]
@klemenkotar from my understanding this is done, please reopen if not.

**Comment by klemenkotar** [comment]
@Lucaweihs Yes al this code is in master now. There is a little bit of clean up left to do (we have some unused code inside [cache_utils](https://github.com/allenai/allenact/blob/master/utils/cache_utils.py), but we can do that in a larger cleanup commit perhaps.
