### ISSUE TITLE
Possible bug in how max-tasks is being set in objectnav dataset task samplers

### ISSUE THREAD

**Issue by prithv1** [allenai/allenact#198]
## Problem

I think the max-tasks parameter is being set incorrectly in the `ObjectNavDatasetTaskSampler` definition. Here's the line:

https://github.com/allenai/allenact/blob/ee736e6a3aeed29b3661ee18fa0dc0a68a40201e/plugins/robothor_plugin/robothor_task_samplers.py#L338

Right now, validation (I think) and test evaluation runs only over a subset of all the provided episode configs -- 240 to be precise on val. This is happening since 
``self.max_tasks = sum(len(scene_episodes) for scene_episodes in self.episodes)``
only considers 16 episodes (length of the keys in `self.episodes`) per-scene.

## Steps to reproduce

The metric json stored after running evaluation with an objectnav checkpoint trained for a few steps contains fine-grained results for only 240 episodes.

## Expected behavior

I think ``self.max_tasks = sum(len(scene_episodes) for scene_episodes in self.episodes)`` should be replaced with ``self.max_tasks = sum(len(self.episodes[scene]) for scene in self.episodes)`` akin to https://github.com/allenai/allenact/blob/ee736e6a3aeed29b3661ee18fa0dc0a68a40201e/plugins/robothor_plugin/robothor_task_samplers.py#L767

**Comment by klemenkotar** [comment]
@anikem @jordis-ai2 I am handling this since I wrote the code

**Comment by jordis-ai2** [comment]
Yes, it looks like a bug. Just made a PR with a fix.

**Comment by klemenkotar** [comment]
@jordis-ai2 Oh I just made a PR too. Yes I totally agree it is a bug. This was fixed for the pointnav dataset task sampler, but not the objectnav. Anyways I will close my PR because I think that @jordis-ai2 has added other things in his as well
