### ISSUE TITLE
Arbitrary Action Space

### ISSUE THREAD

**Issue by Lucaweihs** [allenai/allenact#222]
## Problem

Currently we do not natively support non-categorical action spaces.

## Desired solution

`Task`s already have an `action_space` command, so we should be able to use this to define the action tensor in the `RolloutStorage`. Once this is done, a model need only return a `Distribution` which can sample an action in this space (and determine the log-prob of that action) and everything should work almost identically to as with categorical variables (🤞).

## Additional context

Arbitrary action spaces will also allow us to remove the special multi-agent code we have as everything should be better handled under this general framework.

**Comment by jordis-ai2** [comment]
Working on it!

**Comment by jordis-ai2** [comment]
I'm making code changes in a way that I'm going to break backwards compatibility with existing models:
- I'm still keeping a step dimension in all tensors
- I'm removing the agent dimensions from all tensors (including masks)
- I'm passing actions as flattened tensors (similar to what `gym.spaces.flatten` does, but not identical, e.g. my `Discrete` is just flattened to the sparse representation (a single int)), making it work in the same way as `MultiDiscrete`
- Expert actions should follow the same convention (I saw some examples where a `Discrete` action was returned as in `gym.spaces.flatten(Discrete, x)`

I'm not happy with breaking (again) backwards compatibility (especially without being sure that this is what we want in the future, and taking into account the number of changes I need to make in other parts of the code), so I will create a PR draft for us to discuss the state of things (it will contain a substantial amount of broken code at this point).

**Comment by jordis-ai2** [comment]
In my first design for arbitrary action spaces, I observe a drop in performance of 150 -> 645 fps. Will redo development.
