### ISSUE TITLE
how to do multi-agent tasks?

### ISSUE THREAD

**Issue by liuxz-cs** [allenai/allenact#225]
Excuse me, I want to know how to use allenact framework to perform multi-agent task？ I see in the website that it can support the multi-agent setting.

**Comment by jordis-ai2** [comment]
This feature is currently under major rewriting, but for a simple example with independent agents you can take a look at the config [https://github.com/allenai/allenact/blob/master/projects/tutorials/navtopartner_robothor_rgb_ppo.py](https://github.com/allenai/allenact/blob/master/projects/tutorials/navtopartner_robothor_rgb_ppo.py). Please note that this is a rather limiting way to train multiple agents and a hopefully much improved pipeline is upcoming. I ghope it nevertheless sheds some light: Currently you need to define a task that takes N agents (all with the same single-agent action space), use appropriate sensors to provide the observations and make sure that your environment is correctly configured for multiple agents. In the near future we wish to move to a design where we just define a multi-agent action space, so beware that the current scheme will be broken in future releases...

**Comment by jordis-ai2** [comment]
I'll close this issue since it's covered by [https://github.com/allenai/allenact/issues/222](https://github.com/allenai/allenact/issues/222)

**Comment by jordis-ai2** [comment]
I'm reopening, since I did not include a tutorial/documentation in [https://github.com/allenai/allenact/issues/222](https://github.com/allenai/allenact/issues/222).

**Comment by jordis-ai2** [comment]
[PR231](https://github.com/allenai/allenact/pull/231) provides a full tutorial with two policies (continuous control).
