### ISSUE TITLE
Error with robothor_environment/cache_utils:  retry_dist() takes 2 positional arguments but 3 were given

### ISSUE THREAD

**Issue by ekolve** [allenai/allenact#239]
This line:

https://github.com/allenai/allenact/blob/master/utils/cache_utils.py#L162

calls this function:

https://github.com/allenai/allenact/blob/master/plugins/robothor_plugin/robothor_environment.py#L139

which only expects 2 arguments, but 3 are given.  This happens when training a pointnav model.

**Comment by jordis-ai2** [comment]
Good catch! This must have stayed there after a recent update. I think it's a quick fix 👍

**Comment by jordis-ai2** [comment]
Can you share some more details about the experiment you're running? After inspecting, I haven't seen any pointnavtask-related code calling the wrappeing funtion of https://github.com/allenai/allenact/blob/master/plugins/robothor_plugin/robothor_environment.py#L139

**Comment by jordis-ai2** [comment]
I'm tentatively fixing the call to native_distance_function (which should in any case expect two parameters), but I haven't been able to determine where in the code we use distance_to_object in a pointnav task.
