### ISSUE TITLE
Documentation request

### ISSUE THREAD

**Issue by joel99** [allenai/allenact#284]
Hello, Allenact often relies on a `VISIBILITY_DISTANCE` parameter. Is this measured from agent center to target object center? That seems like a sensible default, but coming from the Habitat MP3D task where object viewpoints are involved, I wasn't sure.

**Comment by Lucaweihs** [comment]
Hi @joel99,

If I'm understanding what you're saying, it sounds correct to me. Quoting from the [iTHOR documentation](https://ai2thor.allenai.org/ithor/documentation/concepts) (visibility is computed in the same way in iTHOR and RoboTHOR):


> ## Object Visibility
> 
> An object is considered Visible when it satisfies three conditions: It must be within the Camera’s viewport (camera field of view), it must be within a radius around the agent’s central vertical axis (default: 1.5 meters radius), and a ray emitted from the camera must hit the object without first hitting another obstruction.
> 
> A note about the “threshold of distance” for the second condition: The initialization value used to determine visibility distance is visibilityDistance. This value defines the radius of a cylinder centered about the y axis of the agent.
> 
> Note that an object rendered in an image will not always be Visible to the Agent. For example, an object outside the 1.5 meter threshold could be seen in an image, but will be reported as not-visible to the Agent.

**Comment by joel99** [comment]
I missed this piece, but I think it'd still be helpful to clarify whether visibility is fairly flexible (can parts of an object be visible?) or a binary state determined by distance to object center of mass.

**Comment by Lucaweihs** [comment]
Gotcha, yes clarifying that an object is considered visible even when it partially (but not totally) occluded is a good idea. From your perspective as someone who has recently looked for this documentation, where would you find most helpful for this documentation to be placed?

**Comment by joel99** [comment]
Sorry for the delay: I expect these kinds of details to show up in the API documentation e.g. https://ai2thor.allenai.org/robothor/documentation. It'd also be helpful to note the two endpoints used in the distance measurement! Thanks!

**Comment by Lucaweihs** [comment]
@mattdeitke could you update the above https://ai2thor.allenai.org/robothor/documentation so that the section on visibility distance links to the more complete discussion under the ithor documentation?

**Comment by mattdeitke** [comment]
Yes. Was somewhat holding off on this because I think it's best to merge iTHOR, RoboTHOR, and ManipulaTHORs documentations together into a single documentation that supports filtering actions/parameters/sections specific to {iTHOR, RoboTHOR, ManipulaTHOR}. The current approach just leads to a lot of duplicated content everywhere.

**Comment by mattdeitke** [comment]
The RoboTHOR docs should now be updated :)

Sorry for the initial confusion.
