### ISSUE TITLE
ValueError: Invalid commit_id: - no build exists for arch=Linux

### ISSUE THREAD

**Issue by rxlqn** [allenai/allenact#302]
I want to test PointNav in RoboTHOR. 

> PYTHONPATH=. python allenact/main.py -o <PATH_TO_OUTPUT> -c -b <BASE_DIRECTORY_OF_YOUR_EXPERIMENT> <EXPERIMENT_NAME>

However, after starting the VectorSampledTask workers, 

> [08/04 15:46:04 INFO:] Starting 0-th SingleProcessVectorSampledTasks generator with args {'mp_ctx': <multiprocessing.context.ForkServerContext object at 0x7f032d7da438>, 'scenes': ['FloorPlan_Train1_1'], 'max_steps': 500, 'sensors': [<allenact_plugins.ithor_plugin.ithor_sensors.RGBSensorThor object at 0x7f033507d8d0>, <allenact_plugins.robothor_plugin.robothor_sensors.GPSCompassSensorRoboThor object at 0x7f032d7da2b0>], 'action_space': Discrete(4), 'seed': 119932381, 'deterministic_cudnn': False, 'rewards_config': {'step_penalty': -0.01, 'goal_success_reward': 10.0, 'failed_stop_reward': 0.0, 'shaping_weight': 1.0}, 'scene_directory': '/home/sjw/workspace/allenact/datasets/robothor-pointnav/debug', 'loop_dataset': True, 'env_args': {'width': 640, 'height': 480, 'rotateStepDegrees': 30.0, 'visibilityDistance': 1.0, 'gridSize': 0.25, 'x_display': '0.0'}, 'allow_flipping': True}  [vector_sampled_tasks.py: 1015]
Process ForkServerProcess-1:1:

I got the errors as follows:

> ValueError: Invalid commit_id: ec298b92fba8c46ea40240ac14802ec6cf9b5f60 - no build exists for arch=Linux
[08/04 15:47:25 ERROR:] Encountered Exception. Terminating train worker 0       [engine.py: 1359]
[08/04 15:47:25 ERROR:] Traceback (most recent call last):

How can fix this problem? 
thanks for your help.

**Comment by Lucaweihs** [comment]
Hi @rxlqn, I notice you closed this issue and #303, does that mean you managed to find a solution?

**Comment by Leeeshuz** [comment]
Hi  @rxlqn, I am stuck in the same problem when trying to run the rearrangement task. How did you solve this?
