### ISSUE TITLE
When I ran the Room Rearrangement task experiment, EOFerror appeared

### ISSUE THREAD

**Issue by twb1235** [allenai/allenact#324]
## Problem
When I run the following command, the error in the screenshot appears。
‘allenact -o rearrange_out -b . baseline_configs/one_phase/one_phase_rgb_resnet_dagger.py ’
The error occurred after the program had been running for some time
## Screenshots
![捕获](https://user-images.githubusercontent.com/57714230/147183238-83058922-b014-44ca-8720-0746ac3083f8.PNG)

Please add the following information:
 OS: Ubuntu 9.3.0-17ubuntu1~20.04
Allenact: 0.4.o
Allenact-plugins: 0.4.0

**Comment by Lucaweihs** [comment]
I'm going to close this issue. Please feel free to reopen if you're still having trouble.
