### ISSUE TITLE
The URL link to download the dataset is invalid

### ISSUE THREAD

**Issue by destination-xy** [allenai/allenact#371]
## Steps to reproduce

1. conda env create --file ./conda/environment-10.2.yml --name allenact2
2. conda activate allenact2
3. pip install -r requirements.txt
4. pip install -r allenact_plugins/ithor_plugin/extra_requirements.txt
5. pip install -r allenact_plugins/robothor_plugin/extra_requirements.txt
6. conda env update --file allenact_plugins/ithor_plugin/extra_environment.yml --name allenact2
7. conda env update --file allenact_plugins/robothor_plugin/extra_environment.yml --name allenact2
8. bash datasets/download_navigation_datasets.sh robothor-pointnav

error :
(allenact2) xy@xy:~/Embodied_AI/allenact$ bash datasets/download_navigation_datasets.sh robothor-pointnav
Downloading RoboTHOR PointNav Dataset ...
--2023-07-19 15:13:23-- https://prior-datasets.s3.us-east-2.amazonaws.com/embodied-ai/navigation/robothor-pointnav-v0.tar.gz
Parsing host prior-datasets.s3.us-east-2.amazonaws.com (prior-datasets.s3.us-east-2.amazonaws.com)... 198.18.1.93
Connecting prior-datasets.s3.us-east-2.amazonaws.com (prior-datasets.s3.us-east-2.amazonaws.com)|198.18.1.93|:443... Connected.
Unable to establish SSL connection.
tar: It doesn't seem like a tar archive
gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now
saved folder: robothor-pointnav
Generating RoboTHOR PointNav Debug Dataset ...
Traceback (most recent call last):
File "/home/xy/Embodied_AI/allenact/./allenact_plugins/robothor_plugin/scripts/make_pointnav_debug_dataset.py",  line 13, in <module>
create_debug_dataset_from_train_dataset(
File "/home/xy/Embodied_AI/allenact/allenact_plugins/robothor_plugin/scripts/make_objectnav_debug_dataset.py", line 24,  in create_debug_dataset_from_train_dataset
assert os.path.exists(downloaded_episodes), (
AssertionError:  '/home/xy/Embodied_AI/allenact/datasets/robothor-pointnav/train/episodes/FloorPlan_Train1_1.json.gz' doesn't seem to  exist or is empty. Make sure you've downloaded to download the appropriate training dataset with  datasets/download_navigation_datasets.sh

The URL to download the dataset is not linked, it seems to be invalid, how to solve the above problem?

**Comment by jordis-ai2** [comment]
Using wget 1.21.4 seems to work for me. For sanity, can you make sure `__TO_OVERWRITE__.tar.gz` is deleted before you call `bash datasets/download_navigation_datasets.sh robothor-pointnav`?

**Comment by destination-xy** [comment]
Thank you very much for your answer, I may have misunderstood before.
